### ISSUE TITLE
github links obsolete

### ISSUE THREAD

**Issue by m4rcc** [imgix/prometheus-am-executor#2]
Hello,

I saw that in the main.go there are two links obsolete,

"github.com/prometheus/alertmanager/template"
"github.com/prometheus/client_golang/prometheus"

From what i see now there is :

"github.com/prometheus/alertmanager/tree/master/template"
"github.com/prometheus/client_golang/tree/master/prometheus"

**Comment by davidbirdsong** [comment]
We haven't built this in a while. Can you patch, test, and submit a PR?

**Comment by otakup0pe** [comment]
Going to take a look at this as part of setting up travis-ci support.

**Comment by colakong** [comment]
The package path used for `import` statements in go code tells go where the `package` definition for _template_ or _prometheus_ packages are; It's not meant to contain vcs-specific details like versioning or branch; That's handled separately in `go.mod` or vendoring. So, the path you use in `import` statements matches the path you'd see on your filesystem in a git clone of a repository, but may not match what you'd see in your browser when navigating a github repository.

If you wanted to target the `master` branch specifically, instead of a tag or pseudo-version, you would keep the path name the same as before, and issue a command like
```
go get -v github.com/prometheus/alertmanager/template@master
```

[This golang blog post](https://blog.golang.org/package-names) has more details on package names/paths :).
