### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ugiopenstack** [imgix/prometheus-am-executor#43]
hi. 
i'm using prometheus-am-executor and i have a question.
i executed reboot script that default file in  ./prometheus-am-executor and i got runtime error.

how can i fix this error?
Should i modify go file?
[root@controller1 prometheus-am-executor]# ./prometheus-am-executor -v examples/reboot 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8c12fc]

goroutine 1 [running]:
main.readCli(0x203000, 0x680, 0xc000235c00)
	/home/prometheus-am-executor/config.go:100 +0x29c
main.readConfig(0x98d0a0, 0x30, 0x30)
	/home/prometheus-am-executor/config.go:117 +0x26
main.main()
	/home/prometheus-am-executor/main.go:36 +0x42

thanks for your help.

**Comment by colakong** [comment]
Hi @ugiopenstack, thank you for pointing this out :smiley_cat: 

That appears to be a regression that was introduced when we [added support for specifying `resolved_signal` in the config file](https://github.com/imgix/prometheus-am-executor/pull/44). Settings in the config file were being checked, even when a config file wasn't specified. This resulted in the nil dereference error.

I've [opened a pull request](https://github.com/imgix/prometheus-am-executor/pull/44) to take care of that error.

To avoid the error, you could do one of:
a) Use a build from an older version of prometheus-am-executor from before the regression (v1.0.0)
b) Use the config file option instead of specifying commands as an argument to prometheus-am-executor
c) Build prometheus-am-executor from a checkout of [my branch with the fix](https://github.com/imgix/prometheus-am-executor/tree/cnelson/fix_nil_ref_no_configfile), if you don't want to wait for it to be merged in to the main branch first
d) Wait until the PR is merged in, then just build and run like you were attempting to before ^^

**Comment by colakong** [comment]
Version [v2.0.2 contains the fix](https://github.com/imgix/prometheus-am-executor/tree/v2.0.2), so option d) might be easiest for you :)

**Comment by ugiopenstack** [comment]
i checked that v2.0.2 contains fixed. Is was a great help :) Thanks!!
